# Generated by Django 5.2.1 on 2025-05-14 03:01

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("user_type", models.CharField(default="employee", max_length=20)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("department_name", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("created_date", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "Department",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("department_name",), name="unique depart"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Employees",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(blank=True, max_length=255, null=True)),
                ("designation", models.CharField(max_length=255)),
                ("date_of_birth", models.DateTimeField()),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Other", "Other"),
                        ],
                        max_length=8,
                        null=True,
                    ),
                ),
                (
                    "nationality",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "iqama_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("mob_no", models.CharField(blank=True, max_length=16, null=True)),
                ("joining_date", models.DateTimeField()),
                ("work_status", models.BooleanField(default=True)),
                ("basic_salary", models.FloatField(default=0)),
                ("gosi_applicable", models.BooleanField(default=True)),
                ("created_date", models.DateTimeField(auto_now=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="department_id",
                        to="attendanceapp.department",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_details",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "EmployeeDetail",
                "verbose_name_plural": "EmployeeDetails",
                "db_table": "employee_details",
            },
        ),
        migrations.CreateModel(
            name="AttendanceRecords",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now=True)),
                ("check_in_time", models.TimeField(blank=True)),
                ("check_out_time", models.TimeField(blank=True)),
                ("work_hours", models.FloatField(default=0)),
                ("overtime_hours", models.FloatField(default=0)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Present", "Present"),
                            ("Absent", "Absent"),
                            ("Late", "Late"),
                            ("On Leave", "OnLeave"),
                        ],
                        max_length=16,
                        null=True,
                    ),
                ),
                (
                    "employee_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_idss",
                        to="attendanceapp.employees",
                    ),
                ),
            ],
            options={
                "verbose_name": "AttendanceRecord",
                "verbose_name_plural": "AttendanceRecords",
                "db_table": "attendance_records",
            },
        ),
        migrations.CreateModel(
            name="PayrollRecords",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.CharField(blank=True, max_length=255, null=True)),
                ("basic_salary", models.FloatField(default=0)),
                ("total_days", models.IntegerField(default=0)),
                ("present_days", models.IntegerField(default=0)),
                ("absent_days", models.IntegerField(default=0)),
                ("gosi_deduction", models.FloatField(default=0)),
                ("allowance", models.FloatField(default=0)),
                ("deduction", models.FloatField(default=0)),
                ("net_salary", models.FloatField(default=0)),
                (
                    "employee_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_ids",
                        to="attendanceapp.employees",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payroll Record",
                "verbose_name_plural": "payroll Records",
                "db_table": "payroll_records",
            },
        ),
    ]
