# Generated by Django 5.2.1 on 2025-05-14 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendanceapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payrollrecords",
            name="created_date",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="attendancerecords",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Present", "Present"),
                    ("Absent", "Absent"),
                    ("Late", "Late"),
                    ("On Leave", "OnLeave"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="LeaveMangement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "leave_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Sick", "Sick"),
                            ("Casual", "Casual"),
                            ("Emergency", "Emergency"),
                            ("Other", "Other"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("leave_days", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Pending", "Pending"),
                            ("Approved", "Approved"),
                            ("Rejected", "Rejected"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
                ("created_date", models.DateTimeField(auto_now=True)),
                (
                    "employee_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_id_leave",
                        to="attendanceapp.employees",
                    ),
                ),
            ],
            options={
                "verbose_name": "Leave Management",
                "verbose_name_plural": "Leave Managements",
                "db_table": "leave_management",
            },
        ),
    ]
