# Generated by Django 5.2.1 on 2025-06-09 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendanceapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="user_name",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="customuser",
            name="first_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="last_name",
            field=models.CharField(max_length=255),
        ),
    ]
