# Generated by Django 5.2.1 on 2025-05-14 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendanceapp", "0002_payrollrecords_created_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_name", models.CharField(max_length=255)),
                ("device_ip", models.CharField(max_length=255)),
                ("device_port", models.CharField(max_length=255)),
                ("sync_interval", models.DateTimeField(blank=True, null=True)),
                ("last_sync_interval", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "device_setting",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("device_name",), name="unique device"
                    )
                ],
            },
        ),
    ]
