# Generated by Django 5.2.1 on 2025-06-09 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "attendanceapp",
            "0002_customuser_user_name_alter_customuser_first_name_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="user_name",
        ),
    ]
