# Generated by Django 5.2.1 on 2025-06-24 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendanceapp", "0002_alter_employees_date_of_birth_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leavedaysofthisyearwise",
            name="leave_date",
            field=models.DateField(),
        ),
        migrations.AddConstraint(
            model_name="employeeleavedetails",
            constraint=models.UniqueConstraint(
                fields=("employee_id", "employee_leave_type"),
                name="unique_employee_leave_type",
            ),
        ),
    ]
