# Generated by Django 5.2.1 on 2025-06-09 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendanceapp", "0003_remove_customuser_user_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Designation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("designation_name", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "Designation",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("designation_name",), name="unique designation"
                    )
                ],
            },
        ),
        migrations.AlterField(
            model_name="employees",
            name="designation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="desination_id",
                to="attendanceapp.designation",
            ),
        ),
        migrations.CreateModel(
            name="EmployeeLeaveDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("leave_count", models.IntegerField(default=0)),
                (
                    "employee_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_id_leavedetails",
                        to="attendanceapp.employees",
                    ),
                ),
            ],
            options={
                "verbose_name": "Employee LeaveDetail",
                "verbose_name_plural": "Employee LeaveDetails",
                "db_table": "EmployeeLeaveDetails",
            },
        ),
        migrations.AddField(
            model_name="employees",
            name="employee_leave_details",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employee_id_leavedetailsdata",
                to="attendanceapp.employeeleavedetails",
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="LEAVETYPE",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("leave_type", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "LEAVETYPE",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("leave_type",), name="unique leavetype"
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="employeeleavedetails",
            name="employee_leave_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employee_id_leavetype",
                to="attendanceapp.leavetype",
            ),
        ),
    ]
