# Generated by Django 5.2.1 on 2025-06-24 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendanceapp", "0003_alter_leavedaysofthisyearwise_leave_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendancerecords",
            name="check_in_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="attendancerecords",
            name="check_out_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
