# Generated by Django 5.2.1 on 2025-05-14 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendanceapp", "0003_devicesetting"),
    ]

    operations = [
        migrations.AddField(
            model_name="devicesetting",
            name="created_date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
