# Generated by Django 5.2.1 on 2025-06-09 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendanceapp", "0004_designation_alter_employees_designation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="designation",
            name="created_date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
