# Generated by Django 5.2.1 on 2025-06-24 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendanceapp", "0004_alter_attendancerecords_check_in_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendancerecords",
            name="date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
