# Generated by Django 5.2.1 on 2025-06-09 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendanceapp", "0005_designation_created_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeeleavedetails",
            name="employee_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employee_id_leave_details",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
