# Generated by Django 5.2.1 on 2025-06-24 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendanceapp", "0005_alter_attendancerecords_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendancerecords",
            name="date",
            field=models.DateField(auto_now=True),
        ),
    ]
