# Generated by Django 5.2.1 on 2025-06-09 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendanceapp", "0006_alter_employeeleavedetails_employee_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="employees",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="uploads/"),
        ),
        migrations.AddField(
            model_name="employees",
            name="filename",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="employees",
            name="upload_date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
