# Generated by Django 5.2.1 on 2025-06-28 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendanceapp", "0007_alter_attendancerecords_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="employees",
            name="address",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
